--local gg = require("vim-gitgutter")

--gg.on_attach(function(bufnr)
    --vim.keymap.set("n", "gnh", ":GitGutterNextHunk<cr>", {buffer = bufnr, desc = '[G]o to [N]ext [H]unk'})
    --vim.keymap.set("n", "gph", ":GitGutterPrevHunk<cr>", {buffer = bufnr, desc = '[G]o to [P]revious [H]unk'})
    --vim.keymap.set("n", "gsh", ":GitGutterStageHunk<cr>", {buffer = bufnr, desc = '[G]it [S]tage [H]unk'})
    --vim.keymap.set("n", "guh", ":GitGutterUndoHunk<cr>",  {buffer = bufnr, desc = '[G]it [U]ndo [H]unk'})
    --vim.keymap.set("n", "gp", ":GitGutterPreviewHunk<cr>", {buffer = bufnr, desc = '[G]it [P]review'})
    --vim.keymap.set("n", "<leader>tgh", ":GitGutterLineHighlightsToggle<cr>", {buffer = bufnr, desc = '[T]oggle [G]it [H]ighlight'})
--end)

vim.keymap.set("n", "gnh", ":GitGutterNextHunk<cr>", {desc = '[G]o to [N]ext [H]unk'})
vim.keymap.set("n", "gph", ":GitGutterPrevHunk<cr>", {desc = '[G]o to [P]revious [H]unk'})
vim.keymap.set("n", "gsh", ":GitGutterStageHunk<cr>", {desc = '[G]it [S]tage [H]unk'})
vim.keymap.set("n", "guh", ":GitGutterUndoHunk<cr>",  {desc = '[G]it [U]ndo [H]unk'})
vim.keymap.set("n", "ghp", ":GitGutterPreviewHunk<cr>", {desc = '[G]it [H]unk [P]review'})
vim.keymap.set("n", "<leader>tgh", ":GitGutterLineHighlightsToggle<cr>", {desc = '[T]oggle [G]it [H]ighlight'})
